user: "nms"                 # Username for all Switches
password: "hpIMC!!!"
tftp_server: "10.0.30.30"
tftp_src_vrf: "default"
tftp_dir: "/mnt/t"
out_dir: "/home/wade"
aliases:
  - "conf t"
  - "alias  kick        do port-access log-off client mac $1; show port-access client"
  - "alias  logout      end ; exit"
  - "alias  logs        show logg | excl nae-script | ex nms | ex hpe-restd"
  - "alias  logsn       show logg -n $1 | excl nae-script | ex nms | ex hpe-restd"
  - "alias  logsrn      show logg -r -n $1 | excl nae-script | ex nms | ex hpe-restd"
  - "alias  np          int $1 ; no power"
  - "alias  run         show run | excl nae-script | ex nms | ex hpe-restd"
  - "alias  sdown       show interface brief | exclude up"
  - "alias  sint        show int br"
  - "alias  sri         show run int"
  - "alias  sril        show run interface lag$1; interface lag $1"
  - "alias  sriv        show run interface vlan$1 ; interface vlan $1"
  - "alias  srv         show run interface vlan$1 ; interface vlan $1"
  - "alias  sup         show interface brief | exclude down"
  - "alias  svp         show vlan port"
  - "alias  this        show running-config current-context"
  - "alias  users       do show port-access clients"
  - "alias  users2      do show aaa authentication port-access interface all client-status"
  - "alias  yp          int $1 ; power"
