---
- name: First delete VLAN 44, then configure VLAN 45, and lastly create VLAN 46
  aoscx_config:
    before:
      - no vlan 44
    parents:
      - vlan 45
    lines:
      - name testvlan
      - description test_vlan
    after:
      - vlan 46

- name: Back up running-config, then create VLAN 100, and save running-config to startup-config if change was made
  aoscx_config:
    backup: True
    lines:
      - vlan 100
    backup_options:
      filename: backup.cfg
      dir_path: /users/Home/
    save_when: changed

- name: Compare running-config with saved config
  aoscx_config:
    diff_against: intended
    intended_config: /users/Home/backup.cfg

- name: Configure VLAN 2345 and compare resulting running-config with previous running-config
  aoscx_config:
    lines:
      - vlan 2345
    diff_against: running

- name: Upload a config from local system file onto device
  aoscx_config:
    src:  /users/Home/golden.cfg

- name: Update interface 1/1/4, matching only if both "parents" and "lines" are present
  aoscx_config:
    lines:
      - ip address 4.4.4.5/24
    parents: interface 1/1/4
    match: strict

- name: Configure a multi-line banner
  aoscx_config:
    lines:
      - hello this is a banner_motd
      - this is banner line 2 banner_motd
      - this is banner line 3 banner_motd
    before: "banner motd `"
    after: "`"
