---
# ansible_connection should be httpapi
- hosts: 6300T
  roles:
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

    - name: Copy Running Config to TFTP server as Temporary Config
      aoscx_backup_config:
        config_name: 'running-config'
        config_type: 'cli'
        remote_output_file_tftp_path: 'tftp://{{tftp_server}}/{{hostname}}_temp_config.cli'
        # output_file: '{{out_dir}}/{{hostname}}_running.cli'
        vrf: '{{tftp_src_vrf}}'

    - name: Get checksum of stored GOLDEN config
      stat:
        path : "configs/{{hostname}}.cli"
        checksum_algorithm: sha256
      register: golden

    - name: Get checksum of pulled RUNNING config
      stat:
        path : "{{tftp_dir}}/{{hostname}}_temp_config.cli"
        checksum_algorithm: sha256
      register: running

    - set_fact:
        golden_sha: "{{ golden.stat.checksum }}"
        running_sha: "{{ running.stat.checksum }}"

    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: "{{ golden.stat }}"
        verbosity: 4
    # - name: Restore Stored Golden Config to Running through TFTP
    #   aoscx_upload_config:
    #     config_name: 'running-config'
    #     remote_config_file_tftp_path: 'tftp://192.168.1.2/switch_config.conf'
    #     vrf: 'mgmt'
    #   when:  golden_sha != running_sha