hostname: SLCIMASW01

local_users:
  admin:
    password: "ciphertext AQBapeKCiG/38rlgYLoa08sSkMUb1nXg5g/OEQvOIk+zvDctYgAAAKJ2WQm6H0Oo56PguzJIYVde+z1z5Javmj8ZorTIgc+b01bH7C+LQtle2itSFr+cH7MnIOPzrNE14kdr7xQMG8hBcGOSJ1/B+dIkE6On9eialbYIVlzup8tzRD4WiJtndTBF"
    group: administrators  # default

ntp:
  servers:
    - 10.41.102.5
    - 10.41.102.6
  vrf: default

# -- // TACACS \\ --
# tacacs:
#   global:
#     tracking: true
#     key: "plaintext $redacted"
#     vrf: mgmt
#     source: interface vlan40
#   servers:
#     - host: cppm1.kabrew.com
#       group: cppm-tac
#       vrf: mgmt
#     - host: cppm2.kabrew.com
#       group: cppm-tac
#       vrf: mgmt

  # -- // some not all global options built in template for svr specific \\ --
radius:
  global:
    # tracking: true
    # tracking_interval: 300
    # tracking_retries: 1
    # tracking_user: radius-tracking-user
    # tracking_pass: "plaintext Red@ct3d"
    # cppm_user: dur-admin
    # cppm_pass: "plaintext Red@ct3d"
    # vrf: mgmt
    key: "ciphertext AQBapQStKrVvYzEfJYjUZaEAuIisMceugE9go+MfB73LTNaUCAAAAK/aHG60HuVW"
    source: interface vlan40
    # timeout: 5
    # retries: 1
    # port: 1812
    # tls_timeout: 5
    # auth_type: <pap|chap> (Default: pap)
    # service_type: in-access-request
  servers:
    - host: 10.41.254.31
      # rfc3576_key: "plaintext $redacted"
      group: ADAUTH
      # vrf: mgmt
      # secure: "ipsec encryption spi 256 md5 plaintext P@ssW0rd"

aaa:
  lines:
    - "aaa authentication login console group local ADAUTH"
  dot1x_enable: false
  mac_enable: false

vlans:
  - pvid: 109
    name: RFT-Allot-DMZ
  - pvid: 400
    name: mgmt
  - pvid: 401
    name: system_mux401
  - pvid: 402
    name: system_mux402
  - pvid: 403
    name: system_mux403
  - pvid: 404
    name: system_mux404
  - pvid: 430
    name: walled_garden
  - pvid: 440
    name: wg_wan
  - pvid: 450
    name: Admin
    ip_mask: 10.41.100.248/24
    ipv6_mask: 2001:5b0:3eff:fff6::248/64
  - pvid: 455
    name: calea
  - pvid: 460
    name: dmz
  - pvid: 471
    name: storage
  - pvid: 472
    name: vMotion
  - pvid: 475
    name: can-bus-controller
  - pvid: 476
    name: TG3-primary
  - pvid: 477
    name: TG3-secondary
  - pvid: 480
    name: Terminal_access
  - pvid: 481
    name: healthmon481
  - pvid: 482
    name: healthmon482
  - pvid: 483
    name: healthmon483
  - pvid: 484
    name: healthmon484
  - pvid: 485
    name: healthmon485
  - pvid: 486
    name: healthmon486
  - pvid: 490
    name: Mgmt_wan

stp:
  - "spanning-tree mode rpvst"
  - "spanning-tree"
  - "spanning-tree vlan 400,440,450,460,475-477,481-486,490"
  - "spanning-tree vlan 400 priority 0"
  - "spanning-tree vlan 440 priority 0"
  - "spanning-tree vlan 450 priority 0"
  - "spanning-tree vlan 460 priority 0"
  - "spanning-tree vlan 475 priority 0"
  - "spanning-tree vlan 476 priority 0"
  - "spanning-tree vlan 477 priority 0"
  - "spanning-tree vlan 481 priority 0"
  - "spanning-tree vlan 482 priority 0"
  - "spanning-tree vlan 483 priority 0"
  - "spanning-tree vlan 484 priority 0"
  - "spanning-tree vlan 485 priority 0"
  - "spanning-tree vlan 486 priority 0"
  - "spanning-tree vlan 490 priority 0"

vsf:
  split_detect: mgmt
  # secondary: 2
  members:
    - member: 1
      type: jl726a
      # link1: 1/1/51-1/1/52
    # - member: 2
      # type: jl726a
      # link2: 1/1/51-1/1/52

dns:
  domain: hneng.net
  servers:
    - host: 10.41.254.1
      # vrfs: [default, mgmt]
    # - host: 10.0.30.52
    #   vrfs: [default, mgmt]
    # - host: 10.0.30.101
    #   vrfs: mgmt

static_routes:
  v4:
    - "0.0.0.0/0 10.41.100.250"
  v6:
    - "::/0 2001:5b0:3eff:fff6::1"

snmp:
  include: snmpj2.j2
  # - "snmp-server community jupcom"
  # - "snmp-server host 10.41.254.15 inform version v2c community jupcom"

# simplified interface variable concat shown below requires custom parser
interfaces:
  - port: lag 1
    lines:
      - no shutdown
      - vlan trunk native 1
      - vlan trunk allowed 400,450,471
      - lacp mode active
  - port: 1/1/1 - 1/1/51
    lines:
      - no shutdown
      - mtu 9198
  - port: 1/1/1 - 1/1/42, 1/1/45 - 1/1/48
    lines:
      - spanning-tree port-type admin-edge
  - port: 1/1/1 - 1/1/3, 1/1/7, 1/1/34, 1/1/39, 1/1/42
    lines:
      - vlan access 400
  - port: 1/1/4 - 1/1/6, 1/1/8 - 1/1/9, 1/1/28, 1/1/31 - 1/1/32, 1/1/37 - 1/1/38, 1/1/45, 1/1/47 - 1/1/48
    lines:
      - vlan access 450
  - port: 1/1/1 - 1/1/3
    lines:
      - description RX/IAP mgmt primary
  - port: 1/1/4
    lines:
      - description slc00vmesx01-ILO
  - port: 1/1/5 - 1/1/6
    lines:
      - description RX/IAP iLO primary
  - port: 1/1/7
    lines:
      - description TX mgmt primary
  - port: 1/1/8
    lines:
      - description slc00vmesx02-ILO
  - port: 1/1/9
    lines:
      - description TX iLO primary
  - port: 1/1/10
    lines:
      - description extra-healthmon ports-2950-swt
      - vlan trunk native 1
      - vlan trunk allowed 109,450,481-486
  - port: 1/1/11 - 1/1/12
    lines:
      - vlan trunk native 450
      - vlan trunk allowed 400,450,476-477,481-486
  - port: 1/1/11
    lines:
      - description slc00vmesx01-vSwitch0
  - port: 1/1/12
    lines:
      - description slc00vmesx02-vSwitch0
  - port: 1/1/13 - 1/1/14
    lines:
      - vlan trunk native 1
      - vlan trunk allowed 471-472
  - port: 1/1/13
    lines:
      - description slc00vmesx01-vSwitch2
  - port: 1/1/14
    lines:
      - description slc00vmesx02-vSwitch2
  - port: 1/1/27
    lines:
      - description FW1-mgmt
  - port: 1/1/28
    lines:
      - description FW1-admin
  - port: 1/1/29
    lines:
      - description FW1-walled_garden_wan
  - port: 1/1/30
    lines:
      - description FW Facility, healthmon and can-bus
  - port: 1/1/31
    lines:
      - description data-lan1_mgmt
  - port: 1/1/32
    lines:
      - description RFT-DRAC-ilo
  - port: 1/1/33
    lines:
      - description PR1-trunk to dmz-wan,wg-wan,data-dmz
      - vlan trunk native 1
      - vlan trunk allowed 440,460,490
  - port: 1/1/34
    lines:
      - description TXM/RXM-testing
  - port: 1/1/35
    lines:
      - description mgmtrtr-dmz-vpn
      - vlan access 490
  - port: 1/1/36
    lines:
      - description TG1
      - vlan access 476
  - port: 1/1/37
    lines:
      - description SLCICNAT01_gi0
  - port: 1/1/38
    lines:
      - description NAS MGMT
  - port: 1/1/39
    lines:
      - description sniffer-ilo
  - port: 1/1/40 - 1/1/41
    lines:
      - description NAS MGMT,ADMIN,vMotion
      - lag 1
  - port: 1/1/42
    lines:
      - description gps1
  - port: 1/1/43
    lines:
      - description Trunk to MGMT LAN SW 2
      - vlan trunk native 1
      - vlan trunk allowed 400-404,430,440,450,460,471-472,475-477,480-486,490
  - port: 1/1/44
    lines:
      - description trunk-data-lan1
      - vlan trunk native 1
      - vlan trunk allowed 401-404,430,455,480
  - port: 1/1/45
    lines:
      - description CE-PCU_a
  - port: 1/1/46
    lines:
      - description fw1-dmz-vpn
      - vlan access 490
  - port: 1/1/47
    lines:
      - description RX-PDU_a
  - port: 1/1/48
    lines:
      - description TX-PDU_a
  - port: 1/1/51
    lines:
      - description Trunk to MGMT LAN SW 2
      - vlan trunk native 1
      - vlan trunk allowed 400-404,430,440,450,460,471-472,475-477,480-486,490




